displayName=Calcified Rock Despawn Timer
author=SpuitelfRs
description=Show an estimate of the remaining time until a calcified rock despawns
tags=mining,calcified,rock,despawn,timer,afk,bone
version=1.0.1
plugins=com.spuitelf.CalcifiedRockDespawnTimerPlugin
build=standard
